[package]
distribution = "2201.8.4"
org = "ballerinax"
name = "docusign.dsrooms"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["eSignature", "Cost/Freemium", "Documents", "Collaboration", "Digital Signature"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-docusign.dsrooms"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
